# Translation of Odoo Server.
# This file contains the translation of the following modules:
# 	* auth_faceid
#
msgid ""
msgstr ""
"Project-Id-Version: Odoo Server 17.0+e\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2024-09-28 19:24+0000\n"
"PO-Revision-Date: 2024-09-28 19:24+0000\n"
"Last-Translator: \n"
"Language-Team: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: \n"
"Plural-Forms: \n"

#. module: auth_faceid
#. odoo-python
#: code:addons/auth_faceid/controllers/main.py:0
#, python-format
msgid "Access denied."
msgstr "Acceso denegado."

#. module: auth_faceid
#. odoo-javascript
#: code:addons/auth_faceid/static/src/login_faceid/login_faceid.js:0
#, python-format
msgid "An error occurred while verifying the face."
msgstr "Ocurrió un error al verificar el rostro."

#. module: auth_faceid
#. odoo-javascript
#: code:addons/auth_faceid/static/src/login_faceid/login_faceid.xml:0
#, python-format
msgid "Cancel"
msgstr "Cancelar"

#. module: auth_faceid
#. odoo-javascript
#: code:addons/auth_faceid/static/src/login_faceid/login_faceid.xml:0
#, python-format
msgid "Capture"
msgstr "Capturar"

#. module: auth_faceid
#: model:ir.model.fields,field_description:auth_faceid.field_res_users__face_encoding
msgid "Face Encoding"
msgstr "Codificación facial"

#. module: auth_faceid
#. odoo-javascript
#: code:addons/auth_faceid/static/src/login_faceid/login_faceid.xml:0
#, python-format
msgid "FaceID Authentication"
msgstr "Autenticación por FaceID"

#. module: auth_faceid
#. odoo-javascript
#: code:addons/auth_faceid/static/src/login_faceid/login_faceid.js:0
#, python-format
msgid "Failed to access the camera."
msgstr "No se pudo acceder a la cámara."

#. module: auth_faceid
#. odoo-javascript
#: code:addons/auth_faceid/static/src/login_faceid/login_faceid.xml:0
#, python-format
msgid "Loading..."
msgstr "Cargando..."

#. module: auth_faceid
#. odoo-javascript
#: code:addons/auth_faceid/static/src/login_faceid/login_faceid.xml:0
#, python-format
msgid "Log in FaceID"
msgstr "Iniciar sesión con FaceID"

#. module: auth_faceid
#. odoo-python
#: code:addons/auth_faceid/controllers/main.py:0
#, python-format
msgid "No face detected in the captured image."
msgstr "No se detectó ningún rostro en la imagen capturada."

#. module: auth_faceid
#. odoo-python
#: code:addons/auth_faceid/controllers/main.py:0
#, python-format
msgid "No match found for the captured face."
msgstr "No se encontró coincidencia para el rostro capturado."

#. module: auth_faceid
#. odoo-python
#: code:addons/auth_faceid/controllers/main.py:0
#, python-format
msgid "No users with registered face encodings found."
msgstr "No se encontraron usuarios con codificaciones faciales registradas."

#. module: auth_faceid
#. odoo-python
#: code:addons/auth_faceid/controllers/main.py:0
#, python-format
msgid "Session creation error: %(error)s"
msgstr "Error al crear la sesión: %(error)s"

#. module: auth_faceid
#: model:ir.model,name:auth_faceid.model_res_users
msgid "User"
msgstr "Usuario"

#. module: auth_faceid
#. odoo-python
#: code:addons/auth_faceid/controllers/main.py:0
#, python-format
msgid "User %(user)s authenticated successfully."
msgstr "El usuario %(user)s se autenticó correctamente."
